version: '3.10'

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    user: 1000:1000
    volumes:
      - ./static/faces:/app/static/faces 

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
